<?php
$formId = $block->getCurrentFormId();
$fields= $block->getFormDetail($formId);
?>

<form name="input_form" id="input_form" class="feedbackForm" enctype="multipart/form-data" method="post"  autocomplete="off" action="<?php echo $block->getBaseUrl().'form/index/index/' ?>">

    <div class="fieldset">
        <?php foreach($fields as $field):?>
        <h3><?php echo $field->title ; ?></h3>
        <ul class="form-list">
            <?php foreach ($field->fields as $item):?>
                <?php if ($item->type == "select"):?>
                    <li class="<?php echo $item->name ?>">
                        <label class="<?php echo $item->name ?>" ><?php echo $item->title ?></label>
                        <div class="<?php echo $item->name ?>">
                            <select title="<?php echo $item->name ?>" name="<?php echo $item->name ?>" id="<?php echo $item->name ?>" class="<?php echo $item->name ?>">
                                <?php foreach ($item->option as $option):?>
                                    <?php if ($option->isDefault == "true"):?>
                                        <option selected="selected" value="<?php echo $option->value ?>"><?php echo $option->name ?></option>
                                    <?php else:?>
                                        <option value="<?php echo $option->value ?>"><?php echo $option->name ?></option>
                                    <?php endif;?>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </li>
               <?php else: ?>
                <li class="<?php echo $item->name?>">
                    <label class="<?php echo $item->name ?>" for="<?php echo $item->title ?>"><?php echo $item->title ?></label>
                    <div class="<?php echo $item->name ?>">
                        <input type="<?php echo $item->type ?>" id="<?php echo $item->name ?>" name="<?php echo $item->name ?>" <?php if ($item->patterns):?>data-pattern='<?php echo $item->patterns ?>' data-message="<?php echo $item->errorMessage ?>"<?php endif;?> placeholder="<?php echo $item->placeholder ?>">
                    </div>
                </li>
                <?php endif;?>
            <?php endforeach;?>
        </ul>
        <?php endforeach;?>
        <input type="hidden" name="format_id" value="<?php echo $formId->getFormatId()?>">
        <div class="buttons-set form-buttons btn-only">
            <button id="next" class="button" ><span><span>Next</span></span></button>
        </div>
    </div>
</form>

<form id="show_detail" style="display:none" >
<div class="show_detail" >
    <?php foreach($fields as $field):?>
        <h3><?php echo $field->title ; ?></h3>
        <ul class="form-list">
            <?php foreach ($field->fields as $item):?>
                    <li class="<?php echo $item->name?>">
                        <label class="<?php echo $item->name ?>" for="<?php echo $item->title ?>"><?php echo $item->title ?>:</label>
                        <div class="<?php echo $item->name ?>">
                            <div class="form-input" data-name="<?php echo $item->name ?>" ></div>
                        </div>
                    </li>

            <?php endforeach;?>
        </ul>
    <?php endforeach;?>

</div>
</form>
<div class="buttons-set form-buttons btn-only">
    <button id="submit" class="button"><span>Submit</span></button>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Venice_Form/js/form": {}
        }
    }
</script>

