<?php
/**
 * Copyright © 2013-2017 GiaPhuGroup Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \PHPCuong\ProductQuestionAndAnswer\Block\Customer\ListCustomer $block */
?>
<?php if ($block->getQuestions() && count($block->getQuestions())): ?>
    <div class="table-wrapper questions">
        <table class="data table table-questions" id="my-questions-table">
            <thead>
                <tr>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Created') ?></th>
                    <th scope="col" class="col item"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                    <th scope="col" class="col description"><?php /* @escapeNotVerified */ echo __('Question') ?></th>
                    <th scope="col" class="col actions"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getQuestions() as $question): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Created')) ?>" class="col date"><?php /* @escapeNotVerified */ echo date("F d, Y", strtotime($question->getQuestionCreatedAt())); ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Product Name')) ?>" class="col item">
                        <strong class="product-name">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($question->getEntityPkValue()); ?>"><?php echo $block->escapeHtml($question->getProductName()); ?></a>
                        </strong>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Question')) ?>" class="col description question-list">
                        <?php echo $block->escapeHtml(nl2br($question->getQuestionDetail())); ?><br/>
                        <?php echo __('Answers'); ?>:
                        <?php if (!empty($answers = $block->getAnswerList($question->getQuestionId()))): ?>
                            <ul class="parent">
                            <?php foreach ($answers as $answer): ?>
                                <li>
                                    <p><?php echo strip_tags($answer['content'], '<br/><br /><br>');?></p>
                                    <span class="author-name">
                                            <small class="time"><?php echo __('by'); ?> <?php echo $answer['author_name'];?><?php echo __(', on'); ?> <?php echo date("m/d/Y", strtotime($answer['created_at']));?></small>
                                    </span>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <ul>
                                <li><?php echo __('Our administrator will reply your question soon.'); ?></li>
                            </ul>
                        <?php endif; ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col actions">
                        <?php echo $this->helper('PHPCuong\ProductQuestionAndAnswer\Helper\Data')->getStatusText($question->getQuestionStatusId()); ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if (sizeof($block->getQuestions())>=10&&$block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?php echo $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
    <div id="likes-dislikes"></div>
    <script type="text/x-magento-init">
        {
            "#likes-dislikes": {
                "PHPCuong_ProductQuestionAndAnswer/js/process-like-dislike": {
                    "likeDislikeUrl": "<?php /* @escapeNotVerified */ echo $block->getLikeDislikeUrl();?>",
                    "loadingNumberImage": "<?php echo $block->getViewFileUrl('PHPCuong_ProductQuestionAndAnswer::images/loading-number.gif'); ?>"
                }
            }
        }
    </script>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have submitted no questions.') ?></span></div>
<?php endif; ?>
